### ISSUE TITLE
Symlinking the vendor directory into the webroot kinda defeats the purpose of a separate webroot

### ISSUE THREAD

**Issue by dsnopek** [shabananavas/civicrm_d8_install_script#1]
See: https://github.com/shabananavas/civicrm_d8_install_script/blob/616729c5d5d9dde983e2e58721d9cf059047e786/civicrm_setup.sh#L126

The point of having a webroot that's separate from the vendor directory is so that the whole vendor directory, which may have some insecure test files or something, isn't web accessible. Symlinking the whole vendor directory into the webroot, makes it web accessible again! Now, that's not the worst thing in the world, that's the default layout of Drupal when you download the release tarball, but your instructions are for a site with the vendor and webroot separate, so it'd be nice not to do that.

What we do, is use rsync to copy the assets that need to be web accessible into 'WEBROOT/libraries/civicrm' and then change CiviCRM's "Resource URL" setting to point to that. There's a small bug in upstream with doing that, but you're using our fork, so the fix is already in there. :-)

Here's the part of our rebuild script that does the rsync:

https://gitlab.com/mydropwizard/roundearth-drops-8/blob/master/rebuild.sh#L77

Hope that helps!

**Comment by shabananavas** [comment]
You're absolutely right! Thanks so much David. I don't know what I was thinking there. I'll fix it.

**Comment by shabananavas** [comment]
Fixed! Again, thank you so much.
